# Generated by Django 4.2.3 on 2023-07-14 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("flight", "0002_alter_flight_aircraft_alter_flight_arrival_airport_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UniqueFlight",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "departure_datetime",
                    models.DateTimeField(
                        default="1990-01-01 00:00",
                        verbose_name="Departure date and time",
                    ),
                ),
                (
                    "left_seats_F",
                    models.IntegerField(
                        default=0, verbose_name="Left seats of first class"
                    ),
                ),
                (
                    "left_seats_B",
                    models.IntegerField(
                        default=0, verbose_name="Left seats of business class"
                    ),
                ),
                (
                    "left_seats_E",
                    models.IntegerField(
                        default=0, verbose_name="Left seats of economy class"
                    ),
                ),
                (
                    "taken_seats_list",
                    models.CharField(
                        default="", max_length=2000, verbose_name="List of taken seats"
                    ),
                ),
                (
                    "arrival_date",
                    models.DateField(default="1990-01-01", verbose_name="Arrival date"),
                ),
                (
                    "arrival_time",
                    models.TimeField(default="00:00", verbose_name="Arrival time"),
                ),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flight.flight",
                        verbose_name="Flight",
                    ),
                ),
            ],
        ),
    ]
