# Generated by Django 4.2.3 on 2023-07-14 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("city", "__first__"),
        ("airport", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airport",
            name="city",
            field=models.ForeignKey(
                default="", on_delete=django.db.models.deletion.CASCADE, to="city.city"
            ),
        ),
        migrations.AlterField(
            model_name="airport",
            name="code",
            field=models.CharField(max_length=3, unique=True, verbose_name="Код"),
        ),
    ]
