# Generated by Django 4.2.3 on 2023-07-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0002_alter_airport_city_alter_airport_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airport",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
