# Generated by Django 4.2.3 on 2023-07-14 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("country", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=255, verbose_name="City")),
                (
                    "country",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="country.country",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Cities",
            },
        ),
    ]
