# Generated by Django 4.2.3 on 2023-07-14 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0002_alter_airport_city_alter_airport_code"),
        ("aircraft", "0002_alter_aircraft_seat_map_picture"),
        ("flight", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="aircraft",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aircraft",
                to="aircraft.aircraft",
                verbose_name="Aircraft",
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="arrival_airport",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="arrival_airport",
                to="airport.airport",
                verbose_name="Arrival airport",
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="arrival_date_begin",
            field=models.DateField(
                default="1990-01-01", verbose_name="Arrival date begin"
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="arrival_time",
            field=models.TimeField(default="10:00", verbose_name="Arrival time"),
        ),
        migrations.AlterField(
            model_name="flight",
            name="departure_airport",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departure_airport",
                to="airport.airport",
                verbose_name="Departure airport",
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="departure_date_begin",
            field=models.DateField(
                default="1990-01-01", verbose_name="Departure date begin"
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="departure_time",
            field=models.TimeField(default="08:00", verbose_name="Departure time"),
        ),
        migrations.AlterField(
            model_name="flight",
            name="flight_number",
            field=models.CharField(max_length=8, verbose_name="Flight Number"),
        ),
        migrations.AlterField(
            model_name="flight",
            name="price_B",
            field=models.FloatField(
                default="18200", verbose_name="Price business class"
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="price_E",
            field=models.FloatField(
                default="11400", verbose_name="Price economy class"
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="price_F",
            field=models.FloatField(default="22500", verbose_name="Price first class"),
        ),
        migrations.AlterField(
            model_name="flight",
            name="repeat_interval",
            field=models.IntegerField(default=1, verbose_name="Repeat interval"),
        ),
    ]
