# Generated by Django 4.2.3 on 2023-07-14 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aircraft", "0002_alter_aircraft_seat_map_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aircraft",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="aircraft",
            name="seat_count_B",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(3)]
            ),
        ),
        migrations.AlterField(
            model_name="aircraft",
            name="seat_count_E",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(3)]
            ),
        ),
        migrations.AlterField(
            model_name="aircraft",
            name="seat_count_F",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(3)]
            ),
        ),
    ]
