# Generated by Django 4.2.3 on 2023-07-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("datetime", models.DateTimeField(verbose_name="Publication date")),
                ("content", models.TextField(max_length=10000)),
            ],
        ),
    ]
