# Generated by Django 4.2.3 on 2023-07-14 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("unique_flight", "__first__"),
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="birth_day",
            field=models.DateField(default="1990-01-01", verbose_name="Date of birth"),
        ),
        migrations.AlterField(
            model_name="order",
            name="booking_id",
            field=models.CharField(default="", max_length=7, verbose_name="Booking ID"),
        ),
        migrations.AlterField(
            model_name="order",
            name="class_of_service",
            field=models.CharField(
                default="E", max_length=1, verbose_name="Class of service"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="document_id",
            field=models.CharField(
                default="", max_length=11, verbose_name="Document ID"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(default="", max_length=255, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="order",
            name="first_name",
            field=models.CharField(
                default="", max_length=255, verbose_name="First name"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="is_registered",
            field=models.BooleanField(default=False, verbose_name="Is registered"),
        ),
        migrations.AlterField(
            model_name="order",
            name="last_name",
            field=models.CharField(
                default="", max_length=255, verbose_name="Last name"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_hash",
            field=models.CharField(default="", max_length=256, verbose_name="Hash"),
        ),
        migrations.AlterField(
            model_name="order",
            name="registration_time",
            field=models.DateTimeField(
                default="1990-01-01 00:00", verbose_name="Flight registration time"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="taken_seat",
            field=models.CharField(default="", max_length=4),
        ),
        migrations.AlterField(
            model_name="order",
            name="unique_flight",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="unique_flight.uniqueflight",
                verbose_name="Unique flight",
            ),
        ),
    ]
