# Generated by Django 5.0.4 on 2024-05-08 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_alter_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="birth_day",
            field=models.DateField(
                default=datetime.date(1990, 1, 1), verbose_name="Date of birth"
            ),
        ),
    ]
